name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROFILE_VIEWS: "False"
          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_LANGUAGE: "True"
          SHOW_OS: "True"
          SHOW_TIMEZONE: "True"
          SHOW_EDITORS: "True"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_LOC_CHART: "False"
          SHOW_PROJECTS: "True"
          SHOW_LINES_OF_CODE: "True"
          IGNORED_REPOS: "factiverse/BRENDA-server, BRENDA-server, factiverse/upptime-dev, upptime-dev, factiverse/upptime-prod, upptime-prod, SADHAN, factiverse/SADHAN, BRENDA, factiverse/BRENDA, factiverse-demo, factiverse/factiverse-demo, ml-models, factiverse/ml-models, template-python, factiverse/template-python"
